services:

  reverse-proxy:
    image: haproxy
    restart: always
    networks:
        backend: {}
    ports:
    - 8080:8080
    volumes:
    - ./haproxy/reverse/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:rw 

  ingress-proxy:
    image: nginx:latest
    restart: always
    ports:
      - 8090:8090
    networks:
      backend:
        ipv4_address: 172.20.0.33
    volumes:
    - ./nginx/ingress/default.conf:/etc/nginx/conf.d/default.conf:rw
    - ./nginx/ingress/nginx.conf:/etc/nginx/nginx.conf:rw

networks:
  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/24
